

message(STATUS)
set(download_dir ${CMAKE_BINARY_DIR}/download)
set(deps_dir     ${CMAKE_BINARY_DIR}/windows-dependencies)
set(deps_file dart-windows-dependencies.zip)
set(deps_server http://downloads.sourceforge.net/project/scusi)
set(already_downloaded already_downloaded-NOTFOUND CACHE PATH "downloaded" FORCE)
find_file(already_downloaded ${deps_file} "${download_dir}")
if(NOT already_downloaded)
    message(STATUS "Downloading ${deps_file}  from ${deps_server} ...")
    file(DOWNLOAD ${deps_server}/${deps_file} ${download_dir}/${deps_file} SHOW_PROGRESS STATUS status LOG log)
    list(GET status 0 status_code)
    list(GET status 1 status_string)
    if(NOT status_code EQUAL 0)
        file(REMOVE ${download_dir}/${deps_file})
        message(FATAL_ERROR "error: downloading '${deps_file}' failed. status_code: ${status_code}, status_string: ${status_string}. \nLog: ${log} ")
    endif()
    execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf ${download_dir}/${deps_file} WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
    set(openssl ${deps_dir}/OpenSSL-Win32 CACHE STRING "OpenSSL dir" FORCE)
    set(PYTHON_EXECUTABLE ${deps_dir}/Python/python.exe CACHE STRING "Python binary" FORCE)
    file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH})
    file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH}/Debug)
    file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH}/Release)
    configure_file(${openssl}/bin/libeay32.dll ${EXECUTABLE_OUTPUT_PATH} COPYONLY)
    configure_file(${openssl}/bin/libeay32.dll ${EXECUTABLE_OUTPUT_PATH}/Debug COPYONLY)
    configure_file(${openssl}/bin/libeay32.dll ${EXECUTABLE_OUTPUT_PATH}/Release COPYONLY)
endif()
message(STATUS "Using Windows dependencies in ${deps_dir}")
